(function(){var e=true,g=null;Math.floor(Math.random()*2147483648).toString(36);/*
 Portions copyright 2006 Adobe Systems Incorporated
 Copyright 2011 Andy Schmitz
 Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/
function i(a,c){this.target=a;this.m={};this.l={};this.h={};this.k={};this.i=j++;this.name=c;this.B=0;k[this.name]=this;l[this.i]=this;return this}var q={};function r(a){for(var c=[],b=0;b<a.length;b++)c[b]=a[b];return c}function s(a){this.b=a;return this}window.FABridge__invokeJSFunction=function(a){var c=a[0];a=a.concat();a.shift();return l[c>>16].z(c,a)};
window.FABridge__bridgeInitialized=function(a){var c=document.getElementsByTagName("object"),b=c.length,d=[];if(b>0)for(var f=0;f<b;f++)if(typeof c[f].SetVariable!="undefined")d[d.length]=c[f];b=document.getElementsByTagName("embed");f=b.length;c=[];if(f>0)for(var h=0;h<f;h++)if(typeof b[h].SetVariable!="undefined")c[c.length]=b[h];h=d.length;b=c.length;f="bridgeName="+a;if(h==1&&!b||h==1&&b==1)t(d[0],a);else if(b==1&&!h)t(c[0],a);else{var o=false;if(h>1)for(var m=0;m<h;m++){for(var v=d[m].childNodes,
p=0;p<v.length;p++){var n=v[p];if(n.nodeType==1&&n.tagName.toLowerCase()=="param"&&n.name.toLowerCase()=="flashvars"&&n.value.indexOf(f)>=0){t(d[m],a);o=e;break}}if(o)break}if(!o&&b>1)for(d=0;d<b;d++)if(c[d].attributes.getNamedItem("flashVars").nodeValue.indexOf(f)>=0){t(c[d],a);break}}return e};var j=0,k={},l={},u=0;function t(a,c){var b=new i(a,c);i[c]=b;var d=q[c];if(d!=g){for(var f=0;f<d.length;f++)d[f].call(b);delete q[c]}}var w={toString:e,get:e,set:e,call:e};
i.prototype={C:function(){return this.c(this.target.getRoot())},releaseASObjects:function(){return this.target.releaseASObjects()},releaseNamedASObject:function(a){return typeof a!="object"?false:this.target.releaseNamedASObject(a.b)},create:function(a){return this.c(this.target.create(a))},A:function(a){return(this.i<<16)+a},u:function(a,c){if(u>0)throw Error("You are trying to call recursively into the Flash Player which is not allowed. In most cases the JavaScript setTimeout function, can be used as a workaround.");
else{u++;var b=this.target.getPropFromAS(a,c);b=this.handleError(b);u--;return b}},D:function(a,c,b){if(u>0)throw Error("You are trying to call recursively into the Flash Player which is not allowed. In most cases the JavaScript setTimeout function, can be used as a workaround.");else{u++;a=this.target.setPropInAS(a,c,this.d(b));a=this.handleError(a);u--;return a}},q:function(a,c){if(u>0)throw Error("You are trying to call recursively into the Flash Player which is not allowed. In most cases the JavaScript setTimeout function, can be used as a workaround.");
else{u++;var b=this.target.invokeASFunction(a,this.d(c));b=this.handleError(b);u--;return b}},j:function(a,c,b){if(u>0)throw Error("You are trying to call recursively into the Flash Player which is not allowed. In most cases the JavaScript setTimeout function, can be used as a workaround.");else{u++;b=this.d(b);a=this.target.invokeASMethod(a,c,b);a=this.handleError(a);u--;return a}},z:function(a,c){var b,d=this.k[a];if(d!=undefined)b=this.d(d.apply(g,this.c(c)));return b},w:function(a){return this.m[a]},
r:function(a,c){s.prototype=this.w(c);var b=new s(a);return this.l[a]=b},v:function(a){return this.l[a]},p:function(a){for(var c=new x(this,a.name),b=a.accessors,d=0;d<b.length;d++)this.o(c,b[d]);a=a.methods;for(d=0;d<a.length;d++)w[a[d]]==undefined&&this.n(c,a[d]);return this.m[c.typeName]=c},o:function(a,c){var b=c.charAt(0),d;if(b>="a"&&b<="z"){d="get"+b.toUpperCase()+c.substr(1);b="set"+b.toUpperCase()+c.substr(1)}else{d="get"+c;b="set"+c}a[b]=function(f){this.a.D(this.b,c,f)};a[d]=function(){return this.a.c(this.a.u(this.b,
c))}},n:function(a,c){a[c]=function(){return this.a.c(this.a.j(this.b,c,r(arguments)))}},t:function(a){var c=this;if(this.h[a]==g)this.h[a]=function(){c.q(a,r(arguments))};return this.h[a]},s:function(a){if(a.e==undefined){a.e=this.A(this.B++);this.k[a.e]=a}return a.e},d:function(a){var c={},b=typeof a;if(b=="number"||b=="string"||b=="boolean"||b==g||b==undefined)c=a;else if(a instanceof Array){c=[];for(b=0;b<a.length;b++)c[b]=this.d(a[b])}else if(b=="function"){c.type=3;c.value=this.s(a)}else if(a instanceof
x){c.type=1;c.value=a.b}else{c.type=4;c.value=a}return c},c:function(a){var c,b=typeof a;if(b=="number"||b=="string"||b=="boolean"||a==g||a==undefined)c=this.handleError(a);else if(a instanceof Array){c=[];for(b=0;b<a.length;b++)c[b]=this.c(a[b])}else if(b=="object"){for(b=0;b<a.newTypes.length;b++)this.p(a.newTypes[b]);for(var d in a.newRefs)this.r(d,a.newRefs[d]);if(a.type==undefined)c=a.value;else if(a.type==2)c=this.t(a.value);else if(a.type==1)c=this.v(a.value);else if(a.type==4)c=a.value}return c},
f:function(a){this.target.incRef(a.b)},g:function(a){this.target.releaseRef(a.b)},handleError:function(a){if(typeof a=="string"&&a.indexOf("__FLASHERROR")==0){a=a.split("||");u>0&&u--;throw Error(a[1]);}else return a}};function x(a,c){this.a=a;this.typeName=c;return this}x.prototype={call:function(a,c){this.a.j(this.b,a,c)},f:function(){this.a.f(this)},g:function(){this.a.g(this)}};i.addInitializationCallback=function(a,c){var b=k[a];if(b!=undefined)c.call(b);else{b=q[a];if(b==g)q[a]=b=[];b.push(c)}};i.prototype.root=i.prototype.C;i.prototype.releaseASObjects=i.prototype.releaseASObjects;i.prototype.releaseNamedASObject=i.prototype.releaseNamedASObject;i.prototype.create=i.prototype.create;i.prototype.addRef=i.prototype.f;i.prototype.release=i.prototype.g;window.FABridge=i;})();
